# Generated by Django 3.2.6 on 2021-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210923_0646"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_list_preference",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_alert_preference",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
