# Generated by Django 3.2.6 on 2021-08-24 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "birth_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "death_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_adult", models.BooleanField(default=False)),
                (
                    "start_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "end_year",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "runtime_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        db_column="genre",
                        related_name="genres",
                        to="core.Genre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TitleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tsv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.FileField(
                        upload_to="tsvs",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["tsv"]
                            )
                        ],
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TitleName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_original_title", models.BooleanField(default=True)),
                (
                    "attributes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attributes",
                        to="core.TitleType",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.title",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True, related_name="types", to="core.TitleType"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="title",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.titletype",
            ),
        ),
        migrations.CreateModel(
            name="Principal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "job",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("characters", models.TextField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.person",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.title",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="known_for_titles",
            field=models.ManyToManyField(
                blank=True, related_name="known_for_titles", to="core.Title"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="professions",
            field=models.ManyToManyField(
                blank=True,
                db_column="profession",
                related_name="professions",
                to="core.Profession",
            ),
        ),
    ]
