# Generated by Django 3.2.6 on 2021-08-25 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.title"
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="principal",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.person"
            ),
        ),
        migrations.AddField(
            model_name="principal",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.title"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="known_for_titles",
            field=models.ManyToManyField(
                blank=True, related_name="known_for_titles", to="core.Title"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="professions",
            field=models.ManyToManyField(
                blank=True,
                db_column="profession",
                related_name="professions",
                to="core.Profession",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="core.action"
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.title"
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
