# Generated by Django 3.2.6 on 2021-08-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.PositiveBigIntegerField(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="professions",
            field=models.ManyToManyField(
                blank=True,
                db_column="profession",
                related_name="professions",
                to="core.Profession",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                db_column="genre",
                related_name="genres",
                to="core.Genre",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="id",
            field=models.PositiveBigIntegerField(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="type",
            field=models.ForeignKey(
                db_column="type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.titletype",
            ),
        ),
        migrations.AlterField(
            model_name="titlename",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                db_column="attribute",
                related_name="attributes",
                to="core.TitleType",
            ),
        ),
        migrations.AlterField(
            model_name="titlename",
            name="types",
            field=models.ManyToManyField(
                blank=True,
                db_column="titletype",
                related_name="types",
                to="core.TitleType",
            ),
        ),
    ]
