# Generated by Django 3.2.6 on 2021-09-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210922_0737"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="activitylog",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.rating",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.review",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="outdated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="outdated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="principal",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filmography",
                to="core.person",
            ),
        ),
        migrations.DeleteModel(
            name="Action",
        ),
    ]
