# Generated by Django 3.2.6 on 2021-08-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_action_activitylog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tsv",
        ),
    ]
