# Generated by Django 3.2.6 on 2021-08-26 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tsv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_name",
                    models.FileField(
                        upload_to="tsvs",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["tsv"]
                            )
                        ],
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("activated", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
